Sun, 20 Mar 2016 16:13:57 sql.py[line:16] INFO 硬盘上面:[/tmp/hadoop/mydb.db]
Sun, 20 Mar 2016 16:13:57 pyhdfs.py[line:329] INFO GETFILESTATUS /mapreduce/am/history/done_intermediate user.name=hadoop //hadoop1:50070
Sun, 20 Mar 2016 16:15:24 sql.py[line:16] INFO 硬盘上面:[/tmp/hadoop/mydb.db]
Sun, 20 Mar 2016 16:15:24 pyhdfs.py[line:329] INFO GETFILESTATUS /mapreduce/am/history/done_intermediate user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate?user.name=hadoop&op=GETFILESTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:15:24 core_process.py[line:27] ERROR intermediate-done-dir path not exists
Sun, 20 Mar 2016 16:15:24 pyhdfs.py[line:329] INFO LISTSTATUS /mapreduce/am/history/done_intermediate user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate?user.name=hadoop&op=LISTSTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:15:24 pyhdfs.py[line:329] INFO LISTSTATUS /mapreduce/am/history/done_intermediate/hadoop user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop?user.name=hadoop&op=LISTSTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:15:24 pyhdfs.py[line:329] INFO OPEN /mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary?user.name=hadoop&op=OPEN HTTP/1.1" 307 0
Sun, 20 Mar 2016 16:15:24 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop2
Sun, 20 Mar 2016 16:15:26 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary?op=OPEN&user.name=hadoop&namenoderpcaddress=hadoop1:9000&offset=0 HTTP/1.1" 200 339
Sun, 20 Mar 2016 16:21:38 sql.py[line:16] INFO 硬盘上面:[/tmp/hadoop/mydb.db]
Sun, 20 Mar 2016 16:21:38 pyhdfs.py[line:329] INFO GETFILESTATUS /mapreduce/am/history/done_intermediate user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate?user.name=hadoop&op=GETFILESTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:21:38 core_process.py[line:27] ERROR intermediate-done-dir path not exists
Sun, 20 Mar 2016 16:21:38 pyhdfs.py[line:329] INFO LISTSTATUS /mapreduce/am/history/done_intermediate user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate?user.name=hadoop&op=LISTSTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:21:38 pyhdfs.py[line:329] INFO LISTSTATUS /mapreduce/am/history/done_intermediate/hadoop user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop?user.name=hadoop&op=LISTSTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:21:38 pyhdfs.py[line:329] INFO OPEN /mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary?user.name=hadoop&op=OPEN HTTP/1.1" 307 0
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop2
Sun, 20 Mar 2016 16:21:38 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary?op=OPEN&user.name=hadoop&namenoderpcaddress=hadoop1:9000&offset=0 HTTP/1.1" 200 339
Sun, 20 Mar 2016 16:22:17 sql.py[line:16] INFO 硬盘上面:[/tmp/hadoop/mydb.db]
Sun, 20 Mar 2016 16:22:17 pyhdfs.py[line:329] INFO GETFILESTATUS /mapreduce/am/history/done_intermediate user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate?user.name=hadoop&op=GETFILESTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:22:17 core_process.py[line:27] ERROR intermediate-done-dir path not exists
Sun, 20 Mar 2016 16:22:17 pyhdfs.py[line:329] INFO LISTSTATUS /mapreduce/am/history/done_intermediate user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate?user.name=hadoop&op=LISTSTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:22:17 pyhdfs.py[line:329] INFO LISTSTATUS /mapreduce/am/history/done_intermediate/hadoop user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop?user.name=hadoop&op=LISTSTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:22:17 pyhdfs.py[line:329] INFO OPEN /mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary?user.name=hadoop&op=OPEN HTTP/1.1" 307 0
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop2
Sun, 20 Mar 2016 16:22:17 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary?op=OPEN&user.name=hadoop&namenoderpcaddress=hadoop1:9000&offset=0 HTTP/1.1" 200 339
Sun, 20 Mar 2016 16:24:02 sql.py[line:16] INFO 硬盘上面:[/tmp/hadoop/mydb.db]
Sun, 20 Mar 2016 16:24:02 pyhdfs.py[line:329] INFO GETFILESTATUS /mapreduce/am/history/done_intermediate user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate?user.name=hadoop&op=GETFILESTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:24:02 core_process.py[line:28] ERROR intermediate-done-dir path not exists
Sun, 20 Mar 2016 16:24:02 pyhdfs.py[line:329] INFO LISTSTATUS /mapreduce/am/history/done_intermediate user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate?user.name=hadoop&op=LISTSTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:24:02 pyhdfs.py[line:329] INFO LISTSTATUS /mapreduce/am/history/done_intermediate/hadoop user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop?user.name=hadoop&op=LISTSTATUS HTTP/1.1" 200 None
Sun, 20 Mar 2016 16:24:02 pyhdfs.py[line:329] INFO OPEN /mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary user.name=hadoop hadoop1:50070
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop1
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary?user.name=hadoop&op=OPEN HTTP/1.1" 307 0
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:188] INFO Starting new HTTP connection (1): hadoop2
Sun, 20 Mar 2016 16:24:02 connectionpool.py[line:362] DEBUG "GET /webhdfs/v1/mapreduce/am/history/done_intermediate/hadoop/job_1458055135385_0003.summary?op=OPEN&user.name=hadoop&namenoderpcaddress=hadoop1:9000&offset=0 HTTP/1.1" 200 339
